// See https://aka.ms/new-console-template for more information
Console.WriteLine("Day 1:");
Console.WriteLine(Puzzle1.CalculateOne().ToString());
Console.WriteLine(Puzzle1.CalculateTwo().ToString());
Console.WriteLine("\nDay 2:");
Console.WriteLine(Puzzle2.CalculateOne().ToString());
Console.WriteLine(Puzzle2.CalculateTwo().ToString());
Console.WriteLine("\nDay 3:");
Console.WriteLine(Puzzle3.CalculateOne().ToString());
Console.WriteLine(Puzzle3.CalculateTwo().ToString());
Console.WriteLine("\nDay 4:");
Console.WriteLine(Puzzle4.CalculateOne().ToString());
Console.WriteLine(Puzzle4.CalculateTwo().ToString());
Console.WriteLine("\nDay 5:");
Console.WriteLine(Puzzle5.CalculateOne().ToString());
Console.WriteLine(Puzzle5.CalculateTwo().ToString());
Console.WriteLine("\nDay 6:");
Console.WriteLine(Puzzle6.CalculateOne().ToString());
Console.WriteLine(Puzzle6.CalculateTwo().ToString());
Console.WriteLine("\nDay 7:");
Console.WriteLine(Puzzle7.CalculateOne().ToString());
Console.WriteLine(Puzzle7.CalculateTwo().ToString());
Console.WriteLine("\nDay 8:");
Console.WriteLine(Puzzle8.CalculateOne().ToString());
Console.WriteLine("Disabled due to long runtime");
Console.WriteLine("\nDay 9:");
Console.WriteLine(Puzzle9.CalculateOne().ToString());
Console.WriteLine(Puzzle9.CalculateTwo().ToString());
Console.WriteLine("\nDay 10:");
Console.WriteLine(Puzzle10.CalculateOne().ToString());
Console.WriteLine(Puzzle10.CalculateTwo().ToString());
Console.WriteLine("\nDay 11:");
Console.WriteLine(Puzzle11.CalculateOne().ToString());
Console.WriteLine(Puzzle11.CalculateTwo().ToString());
Console.ReadLine();